version: '3'

services:
  nginx:
    container_name: nginx
    build: './nginx'
    ports:
      - 443:443
    depends_on:
      - client
      - server
  client:
    container_name: client
    build:
      context: packages/client
      dockerfile: Dockerfile
      target: dev
    ports:
      - 3000:3000
    volumes:
      - ./packages/client:/app # bind a source code to a container
    depends_on:
      - server
  server:
    container_name: server
    build:
      context: packages/server
      dockerfile: Dockerfile
      target: dev
    env_file:
      - .env
    volumes:
      - ./packages/server:/server
    depends_on:
      - mongodb
  mongodb:
    container_name: mongodb
    image: mongo:5.0
    ports:
      - 27017:27017
    env_file:
      - .env
  mongodb-client:
    container_name: mongodb-client
    image: mongo-express:0.54.0
    ports:
      - 8081:8081
    env_file:
      - .env
    depends_on:
      - mongodb